### PR TITLE
Simplify Code, Fix Bugs, and Improve Performance

### PR DESCRIPTION
**Pull request by flpeters**
Hi,  
I really like the simplicity of your plugin, so I wanted to make it even better, while keeping the original spirit intact.  
This version incorporates the changes you published on spigotmc.org, and fixes some problems the current version has.  
For instance, I specified an api version, which leads to problems if omitted on newer server versions, condensed a lot of redundant code, improved usability for server admins, and improved performance.  
Feel free to comment on any changes I made, to edit, and to publish this.

### CODE REVIEW

**Comment by mukkuzzz** [comment]
@DownThePark are you still maintaining this??? @flpeters you think he is maintaining this repo?

**Comment by flpeters** [comment]
> @flpeters you think he is maintaining this repo?

I'm guessing he isn't. This repo doesn't contain the most recent patches he published on spigotmc. I had to add them in. 
Also, last activity is from 10th Jul 2020 on his GitHub, and ~28th Jul 2020 on spigotmc.org. Could just be taking a break though.

**Comment by DownThePark** [comment]
Hey there! Thanks for your pull request.

It's been while since I've logged into GitHub, so I did not see your pull request until now.

From my first impressions, I think your code looks decent so far. Give me some time to review the rest of your code and I'll see if it's merge-worthy.

**Comment by flpeters** [comment]
Hey, I'm glad your first impression is a good one.

I'm still thinking about some improvements, namely:
- improving some of the error/warning messages, especially changing [this one](https://github.com/flpeters/SetHome/blob/75bdafbc063ed38b86f11c47b4e3f659d6c1feb0/src/main/java/me/downthepark/sethome/SetHome.java#L336), to something like: `"Found an old config file, but it was missing keys unexpectedly. Everything will work normally, but some settings may not have been converted as you intended. Please check the config file to make sure everything is OK."`,
- and the way the `reloadConfig2` function is called should probably be refactored to eliminate the duplicate code [here](https://github.com/flpeters/SetHome/blob/75bdafbc063ed38b86f11c47b4e3f659d6c1feb0/src/main/java/me/downthepark/sethome/SetHome.java#L149) and [here](https://github.com/flpeters/SetHome/blob/75bdafbc063ed38b86f11c47b4e3f659d6c1feb0/src/main/java/me/downthepark/sethome/SetHome.java#L381).

I just haven't gotten around to making those changes yet. 
Do you think the changes I made are reasonable? Please don't hesitate to give feedback on any part of the code / design.

**Comment by mukkuzzz** [comment]
@DownThePark i think it is a good to go

**Comment by DownThePark** [comment]
Hello, @flpeters ! Sorry about the ultra late reply. Long story short, stuff happened in life and I only got back into programming recently, and I remembered that I needed to respond back here. Most of the code looks pretty good! I'm just going to make a few changes and I'll get back to you with the feedback soon, eh? Again, sorry for the ultra late reply and thank you for your patience, my friend! - DownThePark

**Comment by DownThePark** [comment]
Hello, @flpeters !

Sorry about the ultra late reply. Long story short, stuff happened in life and I only got back into programming recently, and I remembered that I needed to respond back here.

Most of the stuff looks pretty good! I'm just going to make a few changes and I'll get back to you with the feedback soon, eh? I know I said that last time, but this time I mean it! Again, sorry for the ultra late reply and thank you for your patience!

-DownThePark

**Comment by DownThePark** [comment]
Alright, so I ended up getting carried away and made a lot more changes to the code than I thought I would lol

Firstly, judging by your GitHub profile, you seem to be a pretty good programmer already lol, but anyhow, here's my review:

Positives:
- Auto config reloading is an interesting idea
- Great job with implementing error checking throughout various parts of the code
- Great idea having the ability to convert the config.yml automatically for the user

Areas of potential improvement:
- It might be simpler to just overload reloadConfig2() by calling this.reloadConfig() within the overloaded function
- The compiled .jar shouldn't be included in the source code, though I'm guessing you had put that their temporarily for simplicity sakes
- I'd ideally like for a number of the functions found in SetHome.class to be included in ~~SetHome.class~~ SetHomeUtils.class for organization.

Feel free to respond with any thoughts or questions, eh?

Thank you for your time,
DownThePark

**Comment by flpeters** [comment]
Hey @DownThePark, glad to hear from you!
This project has been at the back of my mind on and off, once or twice a year, so it's nice to see an update.

- At the time, I didn't have a nice idea for `reloadConfig2`, so I just stuck with it. It did it's job, but as mentioned above, should probably get a refactor. You seem to have done a complete rewrite anyway so figuring out a solution is probably redundant at this point.

- The compiled .jar was really a solution for the desperate few that needed this mod to work, but didn't have the ability to compile or fix the project themselves. I agree it's obviously better to just upload the release to an official mod platform, or GitHub releases.

- I'm not sure what you mean by the last point, and I'm gonna assume that's a typo.

There's a number of things I like about your most recent changes so I'd like to give you some feedback as well.

- The idea I like the most is storing the homes of each user in a separate file, instead of a single one. This makes it much easier to update the on disk values, and basically removes the need for periodically writing one large file to disk when there's a change.

- Deleting the set home was an often requested feature, even if it is technically unnecessary. From a game design perspective it's probably nice to have, so a player can decide to pack their stuff, delete their set home, and go on a journey, without any chance of just teleporting back.

- Checking for updates is also a nice feature, nothing much to add there.


The thing I liked the most about your project in general was it's simplicity. The version I modified had less than 300 LOC in exactly 3 files, and was super simple to understand and work with. The version from this pull request was 450 LOC over 2 files.
Even today, after 3 years, it took me only about 5 minutes to read and understand the entirety of the code base for this pull request (except [this message](https://github.com/flpeters/SetHome/blob/75bdafbc063ed38b86f11c47b4e3f659d6c1feb0/src/main/java/me/downthepark/sethome/SetHome.java#L60C37-L60C155); pretty sure the player is not actually teleported after the time is up).
It made it extremely simple for a third party like me to come along and fix what was necessary, and add stuff I was interested in. I remember that even three years ago it took me almost no time to understand the entire project.


The most recent version seems like a departure from that, with over 850 LOC spread over 5 directories, and 14 files. I've now spent about 45 minutes just looking through the code and trying to figure out what it's doing, with limited success, which is a shame, because you could get away with much less.

The best example of this unnecessary complexity increase is probably the entire `/utilities/MessageUtils.java` file.
The problem you have is: You want to send messages to a player when they do certain actions, and you want those messages to be formatted with the player name and maybe the seconds left on the command cooldown.

Leaving aside the use of `if-else` instead of `switch-case`, and that `displayMessage` is called only exactly once in the entire project for each type of message anyway, notice that `displayMessage` and `formatMessage` actually take almost exactly the same arguments. The `message`, the `player`, and the `seconds`. 

All the places you call `displayMessage` from already know these values, so what would happen if you just called `formatMessage` directly?
You could e.g. replace [this line](https://github.com/DownThePark/SetHome/blob/b8a7c644a8e57c0c84c70f1293e3c310b92a995e/src/main/java/com/downthepark/sethome/utilities/HomeUtils.java#L96)
```java
SetHome.getInstance().messageUtils.displayMessage(MessageUtils.MESSAGE_TYPE.CMD_HOME, player, null);
```
with
```java
player.sendMessage(SetHome.getInstance().messageUtils.formatMessage(SetHome.getInstance().configUtils.MESSAGE_CMD_HOME, player.getName(), Optional.ofNullable(null)));
```
and it should work the same.
Now this looks messy, and it kinda is, but do that with all 9 call sites, and you can delete `displayMessage`, as well as the `MESSAGE_TYPE` enum, and probably the whole `MessageUtils.java` file as well if you want to move the single remaining `formatMessage` method elsewhere.
Since you also know at the callsite if the message requires seconds or not, you could even make two separate `formatMessage` methods, one which takes seconds, and one overload which doesn't, so you don't need to check everytime the method is called.
I'm also not sure what's up with the whole `SetHome.getInstace()` stuff, but if you need a reference to SetHome, why not just pass `this` as an argument when you create the object like in the previous version? That would further simplify to:
```java
player.sendMessage(plugin.messageUtils.formatMessage(plugin.configUtils.MESSAGE_CMD_HOME, player.getName()));
```
which doesn't look so messy anymore. You deleted an unnecessary method thus making things faster, and you've removed a layer of indirection making the entire program easier to understand.

There are other places in the project now with similar problems, like the `/utilities/UpdateChecker.java` and the `/commands/*` files. Please correct me if I went wrong somewhere, and if you'd like, we can continue this discussion.

I hope this feedback helps you, and that I wasn't too harsh!
This really is a cool mod and seeing it get some love after such a long time is nice.

Have a good one
Florian

**Pull request merged**
